version: "3.9"

services:
  server:
    build:
      dockerfile: Dockerfile
    ports:
      - '8080:8080'

  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 'rootroot'
    ports:
      - '3306:3306'