version: "3.9"
#services:
#  server:
#    build:
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
#    depends_on:
#      - db
#
#  db:
#    image: mysql:8.0.32
#    environment:
#      MYSQL_ROOT_PASSWORD: 'rootroot'
#    ports:
#      - '3306:3306'
#    volumes:
#      - mysql:/var/lib/mysql
#
#volumes:
#  mysql:

services:
  mysqldb:
    image: mysql:8.0.32
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=todo
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build:
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '6868:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/todo",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "rootroot",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: